version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 4200:4200
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=chatgo
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chatgo
    volumes:
      - ./db/migrate:/docker-entrypoint-initdb.d
